### ISSUE TITLE
walk_from_positions.py error reading the json file

### ISSUE THREAD

**Issue by sonelu** [HumaRobotics/poppy-examples#3]
When executing the walk_from_positions.py there is an error:
`"could not read file"`

Looking more in if I execute the following code in Python:

```
>>> from pypot.primitive.move import Move
>>> f = open('example-walk-positions.json')
>>> savedPositions = Move.load(f)
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexandrusonea/anaconda/lib/python2.7/site-packages/pypot/primitive/move.py", line 100, in load
    return cls.create(d)
  File "/Users/alexandrusonea/anaconda/lib/python2.7/site-packages/pypot/primitive/move.py", line 93, in create
    move._timed_positions.update(d['positions'])
  File "/Users/alexandrusonea/anaconda/lib/python2.7/site-packages/pypot/utils/interpolation.py", line 42, in update
    other = dict(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 16; 2 is required

```

**Comment by harshnagalla** [comment]
hi, were you able to solve this issue??
